version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    network_mode: "host"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: teste
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data

